### ISSUE TITLE
Confusion matrix cells explanation

### ISSUE THREAD

**Issue by provezano** [PacktPublishing/Data-Analysis-and-Machine-Learning-with-Kaggle#1]
On page 116, the cell descriptions (e.g. True Positive/Negative) are different from what Table 5.1 shows.

• TP (true positives): These are located in the **_upper-left cell_** (should be lower-right cell), containing examples that 
have correctly been predicted as positive ones.
• FP (false positives): These are located in the upper-right cell, containing examples that 
have been predicted as positive but are actually negative.
• FN (false negatives): These are located in the lower-left cell, containing examples that 
have been predicted as negative but are actually positive.
• TN (true negatives): These are located in the **_lower-right cell_** (should be upper-left cell), containing examples that 
have been correctly predicted as negative ones.

**Comment by lmassaron** [comment]
Thank you a lot @provezano for spotting this misprint. I informed the editor in order to promptly take all the appropriate steps to correct it.

**Comment by Sonawane-Karan26** [comment]
Thankyou.

I've added the correct description to confusion matrix table in the file here: [Errata.md](https://github.com/PacktPublishing/The-Kaggle-Book/blob/main/Errata.md)
