### ISSUE TITLE
Errata in The Kaggle Book

### ISSUE THREAD

**Issue by manojent** [PacktPublishing/Data-Analysis-and-Machine-Learning-with-Kaggle#4]
Hello!

I think I have come across some errors in text of the book and would like to highlight them here:

1) Chap 5, page 121, the first paragraph says: "A bad classifier can be spotted by the ROC curve appearing very similar, if not identical, to the diagonal of the chart, which represents the performance of a purely random classifier, as in the **top left** of the figure above; ROC-AUC scores near 0.5 are considered to be almost random results." I think that the **TOP LEFT** should read **TOP RIGHT** to point to the ROC-AUC score of 50% or 0,5

2) Chap 5, page 130, the last line of the note says: ".....YOLO (https://arxiv.org/abs/1506.02640v1), Faster R-CNN https://arxiv.org/abs/1506.01497v1), or **SDD** (https://arxiv.org/abs/1512.02325)." I think the authors meant **SSD** (Single Shot Detection) rather than SDD.

Hope it helps!!

**Comment by lmassaron** [comment]
Thank you very much, @manojent , for spotting these typos. They have gone unnoticed until now, but we are going to correct them immediately, thanks to your great help. The corrections to be implemented should be:

Chap 5, page 121, the first paragraph says: "A bad classifier can be spotted by the ROC curve appearing very similar, if not identical, to the diagonal of the chart, which represents the performance of a purely random classifier, as in the top right of figure 5.3; ROC-AUC scores near 0.5 are considered to be almost random results."

Chap 5, page 130, the last line of the note should say: ".....YOLO (https://arxiv.org/abs/1506.02640v1), Faster R-CNN https://arxiv.org/abs/1506.01497v1), or SSD (https://arxiv.org/abs/1512.02325)."

I've added the corrections in the file here: [Errata.md](https://github.com/PacktPublishing/The-Kaggle-Book/blob/main/Errata.md)

@Sonawane-Karan26, @Parvathyn-packt please take notice of the errors for the update in print and digital; thank you.

**Comment by manojent** [comment]
@lmassaron You are welcome!!!
