### ISSUE TITLE
Chapter 9 - typo and optimization in code, pages 326-327

### ISSUE THREAD

**Issue by HectorLira** [PacktPublishing/Data-Analysis-and-Machine-Learning-with-Kaggle#5]
Hey! Big fan of the book here.

## Typo
In Chapter 9, pages 326-327 in the code snippets there is a typo on the `first_lvl_preds` variable, it is written as `fist_lvl_preds`.

The code says:
```python
fist_lvl_preds = np.zeros((len(X_test), 3))
```
But it should say:
```python
first_lvl_preds = np.zeros((len(X_test), 3))
```
This would imply that the subsequent uses of the variable should also be renamed.

## Optimization

In Chapter 9, page 326 third code snippet, the code looks like this:
```python
second_lvl_oof = np.zeros((len(X_train), 3))
second_lvl_preds = np.zeros((len(X_test), 3))

for k, (train_index, val_index) in enumerate(kf.split(X_train)):
    skip_X_train = np.hstack([X_train, first_lvl_oof])
    model_1.fit(skip_X_train[train_index, :], y_train[train_index])
    second_lvl_oof[val_index, 0] = model_1.predict_proba(skip_X_train[val_index, :])[:, 1]
    
    model_2.fit(skip_X_train[train_index, :], y_train[train_index])
    second_lvl_oof[val_index, 1] = model_2.predict_proba(skip_X_train[val_index, :])[:, 1]
    
    model_3.fit(skip_X_train[train_index, :], y_train[train_index])
    second_lvl_oof[val_index, 2] = model_3.predict_proba(skip_X_train[val_index, :])[:, 1]
```
But it could be optimized if the `skip_X_train` variable is defined outside the for loop. I've rerun the code and arrived at the same results:
![image](https://github.com/PacktPublishing/The-Kaggle-Book/assets/32204890/9cecf38a-179c-404c-80fc-379a16a37479)

**Comment by lmassaron** [comment]
Hi @HectorLira, I am delighted that you are enjoying the Kaggle Book and that you are a big fan of it, and thank you a lot for spotting the typos and suggesting this enhancement. After your suggestion, both have already been implemented in this repository and in the code for the second edition of the book!
